// Generated by CoffeeScript 1.7.1
(function() {
  var b, yolo;

  b = true;

  if (b != null) {
    alert("yolo");
  }

  yolo = function(boolean) {
    alert(boolean);
  };

  yolo(b);

}).call(this);
